services:
  escola.api:
    image: ${DOCKER_REGISTRY-}escolaapi
    build:
      context: .
      dockerfile: src/Escola.API/Dockerfile
    networks:
      - container-network

  postgres:
    image: postgres:latest
    container_name: container-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: DbProject
    ports:
      - "5433:5432"
    networks:
      - container-network
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: container-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "5434:80"
    networks:
      - container-network
    restart: always

networks:
  container-network:
    driver: bridge
